### ISSUE TITLE
[1.1x ToDo]

### ISSUE THREAD

**Issue by Morpheus1101** [Morpheus1101/Avaritia#3]
- [ ]  Add Infinity Hoe of the Green Earth
- [ ]  Finish off Emerald & Diamond Singularity
- [ ]  Add Ex-Niholo Style Hammer                                                                    
- [ ]  Add Tinkers Style Hammer
- [ ]  Add Battle Wrench//Crescent Hammer
- [ ]  Add Infinity Tank - use Long.Max_Value
- [ ]  Add Avaritia BlackHole Chest
- [ ]  Add Neutronium Key for Lockable BlackHole Chest
- [ ]  9x9 Autocraft for AE named: Infinity Assembler
Add in other Mod intergrations as they are released for 1.1x e.g. Thaumcraft

**Comment by ConnorPr** [comment]
What's the plan for the Black Hole Chest? I'm really curious since it says that it can be locked. Is it going to be a lockable chest with a huge inventory?

**Comment by Morpheus1101** [comment]
A lot of these things will be for 1.11.2, but essentially it will have a very large as yet undetermined amount of space, be lockable an cannot be destroyed, unless you say explode a DE reactor

**Comment by IDKZAL** [comment]
I still think Infinity Chest would be a cool thing even tho in 1.7.10 it was a separate mod. :P

**Comment by IDKZAL** [comment]
Oh, and you forgot to add the ability to mine bedrock/unbreakable blocks with the pickaxe.

**Comment by Morpheus1101** [comment]
Idk about that one tbh, i'll have to think that one over.

**Comment by IDKZAL** [comment]
A random question, will you guys just jump over 1.11?  because 1.12 is right around the corner? :D I would really like to know why U want to do all the cool stuff in 1.11 even tho Draconic and other mods are not ported yet :( Can't u guys/developer just stay at one version of Minecraft like in 1.7.10 where all cool mods are? xD and not hop on every updated?

**Comment by Morpheus1101** [comment]
1.7.10 is dead, nobody really does anything for their mod in that versioning.  Currently 1.10.2 is somehwat the norm with 1.11.2 emerging now, 1.12 is still a while away before porting a version over to it will be a thing, but for me, i like to keep current to what is mostly played around the modding community pack wise, which is 1.10.2 atm with 1.11.2 now emerging, so you move with the times.

**Comment by NoplixDE** [comment]
Will u add Auto Dire Crafting Table like in 1.7.10? Would be really cool.

**Comment by Morpheus1101** [comment]
I'm not familiar with Auto Dire Crafting Table

**Comment by NoplixDE** [comment]
Sry I forgot to say it was in an Addon like the Infinity Chest aka https://minecraft.curseforge.com/projects/avaritiaddons
Like in this video:
https://youtu.be/aJIliG2rt9w?t=1326 u will see the concept.

**Comment by superon** [comment]
does this mean stargates are being added?

**Comment by Morpheus1101** [comment]
Lol, well its an interesting thought, but i do believe someone has all ready done that

**Comment by rados33** [comment]
It would be cool if you add multitool  with gui like draconic staff (sorry for bad english)

**Comment by Morpheus1101** [comment]
Thanks for your suggestion rzdos33, but i wont be adding any multitool :)

**Comment by NoplixDE** [comment]
But he still has a good Idea, with the GUI, Maybe add some kind of Option to edit the AOE Range of the Sword/World Breaker/all AOE tools.

**Comment by p455w0rd** [comment]
If we were to make GUIs like DE what would convince a person to use our tools of DE's? This will not be happening. At most, I might make AOE editable in-world somehow (crouch+scroll or something).

**Comment by NoplixDE** [comment]
It would be cool to change the AOE size of everything or at least the hammer, the GUI is not a must I bet there are other ways.

**Comment by p455w0rd** [comment]
Just a little update on things/progress:
- @Fundryi - Morph and I discussed the AOE sizes thing. In short I feel we need to get 1.11.2 out as covers will be taking over for the 1.12 port and tbh, 1.11.2 has already come and gone. So at least for 1.11.2 this will not be happening. I do see several cases where adjustable AOE would be viable, just not at this time. As far as an automated Dire Crafting Table - I love the concept, however that mod's implementation is horrible. Such a feature would have to wait until 1.12, but I think something like a schematic/pattern item that you would insert into a new slot in the Dire Crafting Table would work much better. For now I have added support for auto exporting from the table, but there's no real point to it yet..just know the foundation has been implemented.

- @rados33 As far as GUIs, I mean I'm not a fan since as you stated, this exists in DE already. We're not looking to mimic DE. Tho I do feel your pain..there are just other ways to approach this issue and we will in 1.12. 

- Progress overall has been slow due to many factors, my health being one of the major ones, but I'm back at it now and I'm really hoping to have a release version in the coming days (Ideally today, but I refuse to make a commitment I may not be able to keep)

- TiC integration: Covers (afaik) has no experience with TiC's API, where I have fully integrated my p455w0rd's Things mod with it, so I may be doing the TiC integration, but this will not be happening until 1.12

- Various other integrations: again..for the sake of getting this mod on 1.12, We will likely only be integrating with JEI and CraftTweaker for 1.11.2.

- Backporting the awesome stuff from 1.12 to 1.11.2: 1.11.2 is essentially dead due to Mojang's rapid update roadmap. Due to this, I don't see any real point in backporting - _HOWEVER_ we do accept PRs if someone would wish to do this once Covers finishes the 1.12 update.

- Finally..even though not ideal, this thread is the best place to stay up to date on progress. If you're interested in staying up to date, bookmark this page and check back periodically. You will not be informed of changes to the checklist via notifications as github doesn't send notifications for edited comments.
